```{r, include=FALSE}
# Links
rlink <- "[R](http://r-project.org/){target='_blank'}"
rstudio <- "[RStudio](http://rstudio.org/){target='_blank'}"
cran <- "[CRAN](http://cran.r-project.org/){target='_blank'}"
github <- "[GitHub](http://github.com/){target='_blank'}"
git <- "[Git](https://git-scm.com/)"
```

# Entendendo a coleção *Estudando o ambiente R*

A Coleção *Estudando o ambiente R* não tem como objetivo principal de ensinar análise de dados. Mas sim, proporcionar ao leitor um conhecimento sobre a linguagem `r rlink`, de modo que se possa usufruir todos os recursos que esse ambiente possa proporcionar.

Ainda como complemento, não queremos nesse material, convencê-lo a utilizar a linguagem `r rlink`, pois a melhor linguagem é aquela que você domina. Contudo, pretendemos mostrar que os recursos utilizados pelo `r rlink` não estão mais limitados a própria análise de dados. Um exemplo é esse material, que nesse momento usufruímos da própria linguagem para repassar as nossas experiências sem ao menos ter o domínio sobre linguagens do tipo `HTML`, `CSS`, `JavaScript`, dentre outras, necessárias para uma boa renderização de página *web*. Isso mostra a potencial ferramenta de trabalho que o ambiente `r rlink` pode ser para a vida profissional.

Dessa forma, propormos um entendimento sobre a sintaxe e semântica de como a linguagem `r rlink` é desenvolvida. Com isso, o leitor será capaz após a leitura dos dois primeiros volumes, de estudar um pouco mais sobre essa ciência que nos últimos anos vem ganhando mais evidência, que é a Estatística. Tudo isso devido ao grande volume de informações obtidos nessa era tecnológica. Juntamente com ela, o `r rlink` se tornará uma poderosa ferramenta para entender os padrões que estão por trás dos dados, que por sinal, é a moeda valiosa do momento, ou melhor, sempre foi!

Mas não só apenas análise de dados, aprenderemos também recursos diversos na área da computação, como programação defensiva, desenvolvimento de interfaces gráficas, paralelização, como também recursos na área da estatística sem complexidades teóricas, como o desenvolvimento de gráficos e o uso de banco de dados. Ensinaremos também o desenvolvimento de materiais como artigos, livros, *websites*, *blogs*, *dashboards*. Por fim, chegaremos a maior cobiça de um programador `r rlink`, desenvolver um pacote.

<blockquote>
<p>
<em> Observem que em muitos momentos utilizamos o artigo "o" para a linguagem `r rlink`. Pois é, isso ocorre porque ela também é considerada um software ou ambiente. Daí, também podemos chamá-la de software `r rlink`, ou preferivelmente, ambiente `r rlink`. </em>
</p>
</blockquote>

Os módulos dessa coleção terão os três volumes base para o entendimento do ambiente `r rlink`:

- Volume I: Nível Básico;
- Volume II: Nível Intermediário; e 
- Volume III: Nìvel Avançado.

A seguir, explanaremos sobre cada um dos módulos.

## Volume I: Nível Básico

Esse primeiro volume, que representa o livro corrente, apresenta um breve **histórico** sobre a linguagem, a sua instalação, bem como os recursos que a IDE^[Do inglês, *Integrated Development Environment*, que significa ambiente de desenvolvimento integrado] `r rstudio`, o conhecimento da **sintaxe** e **semântica** da linguagem `r rlink`, compreendendo as estruturas bases da linguagem, sobre o que é um **objeto** e como construir uma **função**, o entendimento sobre **fluxos de controle**. O que é um **pacote**, **carregar** e **anexar** um pacote, e quem são as pessoas que fazem parte da manutenção dessa linguagem, também serão assuntos desse primeiro módulo. **Caminhos de busca**, **ambientes** e *namespaces*, teremos noções básicas. Algo muito interessante, que pode mudar a vida de um programador em `r rlink` são as **boas práticas para a escrita de um código**, tema também abordado nesse módulo.

A ideia desse volume é proporcionar um entendimento básico, um primeiro contato com a linguagem, fazendo com que o leitor possa dar os primeiros passos, executando as primeiras linhas de comando. Mas também, dando o enfoque com erros tão recorrentes, como o entendimento sobre um objeto, ou o anexo de um pacote no caminho de busca. Temas como esses, dentre outros, serão a forma inicial que encontramos, para que posteriormente, seja dado um aprofundamento sobre a estrutura de um objeto `r rlink` bem como a sua manipulação, e adicionado a isso, a inserção de como são os paradigmas da programação nesse ambiente. Essa última parte será estudada, no Volume II, apresentado a seguir.

## Volume II: Nível Intermediário

O volume II é introduzido com uma melhor caracterização do ambiente `r rlink` quanto ao seu **escopo léxico**, como **linguagem interpretada**, como **programação funcional**, como **programação meta-paradigma**, como **programação dinâmica**; apresentaremos **manipulações de objetos em mais detalhe**, bem como o surgimento de alguns outros objetos como *tibble*, **cópias de objetos**. Uma característica do ambiente `r rlink` é que a linguagem pode ser **orientada a objetos** e isso será estudado nesse módulo. Introduziremos ao **desenvolvimento de pacotes R**, e aprofundaremos sobre os **ambientes**. Por fim, mostraremos como desenvolver Projeto do `r rstudio` e integrá-los ao `r github`, e dessa forma, introduziremos sobre o sistema `r git`.

Esse talvez seja o maior volume, dentre os três iniciais, porque apenar de não precisarmos entender mais a ideia dos objetos, que foram retratadas no Volume I, a inserção dos paradigmas da programação para este volume, trará uma maior riqueza de características para o `r rlink`, mostrando a sua versatilidade. Também, daremos um maior detalhamento como manipular objetos, e as otimizações existentes da linguagem, como por exemplo, a modificação no local, que se entendido, poderá perceber que o *loop* no ambiente `r rlink` não é lento quanto parece. Ao final desse volume, falaremos sobre como propagar o seu código com o sistema `r git` na plataforma `r github`, sincronizado com os projetos do `r rstudio`.

## Volume III: Nível Avançado

O Volume III, será a total exploração do manual [R Internals](https://cran.r-project.org/doc/manuals/R-ints.html). Apesar de ser um assunto voltado para membros do [R Core Team](https://www.r-project.org/contributors.html), pretendemos entender como o `r rlink` trabalha nos bastidores. Dessa forma, teremos total controle sobre as nossas rotinas. Contudo, para usários que pretendem entender o  ambiente `r rlink` de forma aplicada, pode avançar esse volume para a leitura dos volumes seguintes.

## Demais volumes

Os demais volumes compreendem lacunas necessárias para serem abordadas com profundidade, tais como: *Documentações no R*, *Desenvolvimento de pacote R*, *Gráficos*, *Banco de dados*, *Interface Gráfica ao Usuário*, *Interface R com outras linguagens*, dentre outros.

## Referências complementares da Coleção {#referencias}

Citaremos alguns livros e materiais utilizados para o desenvolvimento dessa coleção, que alguns podem ser acessados *online* via *bookdown*, tais como:


 - [An Introduction to R](https://cran.r-project.org/doc/manuals/r-release/R-intro.html) (R Core Team)
 - [R Data Import/Export](https://cran.r-project.org/doc/manuals/r-release/R-data.html) (R Core Team)
 - [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-release/R-admin.html)  (R Core Team)
 - [Writing R Extensions](https://cran.r-project.org/doc/manuals/r-release/R-exts.html) (R Core Team)
 - [R Language Definition](https://cran.r-project.org/doc/manuals/R-lang.html) (R Core Team)
 - [R Internals](https://cran.r-project.org/doc/manuals/R-ints.html) (R Core Team)
 
 - [Advanced R](https://adv-r.hadley.nz/) [@hadley2019]
 - [Advanced R Solutions](http://advanced-r-solutions.rbind.io/) [@hadleyetal2021]
 - [R Packages](https://r-pkgs.org/index.html) [@hadley2015]
 - [R for Data Science](https://r4ds.had.co.nz/) [@hadley2017]
 - Extending R [@chambers2016]
 - Software for Data Analysis: Programming with R [@chambers2008]
 - R in a Nutshell [@adler2012]
 - The New S Language (Livro Branco) [@chambers1988]
 - Statistical Models in S (Livro Azul) [@chambers1991]
 - Programming with Data (Livro Verde) [@chambers1998]

Vale salientar que esses três últimos livros, se pudéssemos unir, seria a bíblia do ambiente `r rlink`.

## Pacotes R utilizados para esse curso {#pacutilizados}

Apresentamos uma lista de pacotes, Tabela \@ref(tab:instalar-pacotes), utilizados ao longo da coleção para os exemplos abordados, como também para o próprio desenvolvimento dos livros.

Table: (\#tab:instalar-pacotes) Pacotes a serem instalados para o acompanhamento dos exemplos e exercícios da coleção *Estudando o ambiente R*.

| Pacote | Objetivo para o curso |
|:------:|:---------------------:|
| [lobstr](https://lobstr.r-lib.org/)  | Auxilia no estudo sobre a sintaxe do pacote |
| [codetools](https://cran.r-project.org/package=codetools/)| Auxilia no estudo sobre a sintaxe do pacote |
|[XR](https://cran.r-project.org/package=XR/) | Auxilia no estudo sobre a sintaxe do pacote |
| [rlang](https://rlang.r-lib.org/) | Auxilia no estudo sobre a sintaxe do pacote |
| [sloop](https://sloop.r-lib.org/) | Auxilia a compreender interativamente a programação orientada a objetos |
| [styler](https://styler.r-lib.org) | Auxilia no estilo de código |
| [formatR](https://yihui.org/formatr) | Auxilia no estilo de código |
| [distill](https://rstudio.github.io/distill/) | Criação da página|





