---
output:
  pdf_document: default
  html_document: default
---
# (PART) Programação em R (Nível Básico) {-}


# Instalação e história do R

Em desenvolvimento ...


## Instalação do R e RStudio 

## Como utilizar o R e o RStudio

## História do R


# Introdução ao R

## Como o R trabalha

## Comandos no R e Ambiente Global

### Console e *Prompt* de comando

### Comandos elementares

### Execução de comandos

### Chamada e correção de comandos anteriores

### Ambiente Global (área de trabalho ou *Workspace*)

## Arquivos `.RData` e `.Rhistory`

## Criando e salvando um *script*


# Objetos

## Atributos

### Atributos intrínsecos

## Coersão

## Tipo de objetos

### Vetores

#### Vetores escalares

#### Vetores longos

#### Manipulando vetores

### Matrizes bidimensionais

### Matrizes multidimensionais

### Listas

### Quadro de dados

### Funções

#### Estruturas de controle

#### Como criar funções

#### Escopo léxico
teste

# Importando dados

## Preparação dos dados

## Importando dados


# Boas práticas de como escrever um código

## Nomes de arquivos

## Comentar as linahs de comando

## Nome de objetos

### Sintaxe

# Pacotes

## Estrutura básica de um pacote

## Instalação de um pacote

## Objetivos de um pacote

## Utilizando funções de um pacote

## Carregando e anexando um pacote

## *NAMESPACE* de um pacote

## Usando os operadores `::` e `:::`

# Ambientes e caminho de busca

## A superatribuição

# Interfaces com outras linguagens

# Considerações e preparação para Programação em R (Nível Intermediário)












